from pathlib import Path

path = Path('BuFi/Playback/AudioEngine.swift')
text = path.read_text()

def replace_once(old: str, new: str) -> None:
    global text
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'expected one match, found {count}: {old[:100]!r}')
    text = text.replace(old, new, 1)

replace_once('''    private var itemObservation: NSKeyValueObservation?\n    private var timeControlObservation: NSKeyValueObservation?\n''','''    private var itemObservation: NSKeyValueObservation?\n    private var itemBufferObservations: [NSKeyValueObservation] = []\n    private var timeControlObservation: NSKeyValueObservation?\n''')
replace_once('''        itemObservers.forEach(NotificationCenter.default.removeObserver)\n        systemObservers.forEach(NotificationCenter.default.removeObserver)\n''','''        itemObservers.forEach(NotificationCenter.default.removeObserver)\n        itemBufferObservations.removeAll()\n        systemObservers.forEach(NotificationCenter.default.removeObserver)\n''')
replace_once('''            currentSong = nil\n            queue = []\n            queueIndex = -1\n            lyrics = .empty\n            player.replaceCurrentItem(with: nil)\n''','''            currentSong = nil\n            queue = []\n            queueIndex = -1\n            elapsed = 0\n            duration = 0\n            isBuffering = false\n            playbackError = nil\n            showFullLyrics = false\n            lyrics = .empty\n            activeLyricIndex = -1\n            itemObservation = nil\n            itemBufferObservations.removeAll()\n            itemObservers.forEach(NotificationCenter.default.removeObserver)\n            itemObservers.removeAll()\n            player.replaceCurrentItem(with: nil)\n''')
replace_once('''            self.elapsed = max(0, serverQueue.position)\n            self.duration = self.currentSong?.safeDuration ?? 0\n''','''            self.duration = self.currentSong?.safeDuration ?? 0\n            let restoredPosition = max(0, serverQueue.position)\n            self.elapsed = self.duration > 0 ? min(restoredPosition, self.duration) : restoredPosition\n''')
replace_once('''        player.seek(\n            to: CMTime(seconds: target, preferredTimescale: 600),\n            toleranceBefore: .zero,\n            toleranceAfter: .zero\n        )\n''','''        let tolerance = CMTime(seconds: 0.1, preferredTimescale: 600)\n        player.seek(\n            to: CMTime(seconds: target, preferredTimescale: 600),\n            toleranceBefore: tolerance,\n            toleranceAfter: tolerance\n        )\n''')
replace_once('''        let count = ProcessInfo.processInfo.isLowPowerModeEnabled ? min(defaultCount, 1) : defaultCount\n        guard count > 0 else { return }\n''','''        let thermalState = ProcessInfo.processInfo.thermalState\n        guard thermalState != .serious, thermalState != .critical else { return }\n        let cappedCount = min(max(defaultCount, 0), 2)\n        let count = ProcessInfo.processInfo.isLowPowerModeEnabled ? min(cappedCount, 1) : cappedCount\n        guard count > 0 else { return }\n''')
replace_once('''        // Fetch audio in larger contiguous bursts so the radio can return\n        // to idle sooner, and never extend the network buffer while paused.\n        item.preferredForwardBufferDuration = ProcessInfo.processInfo.isLowPowerModeEnabled\n            ? 45\n            : 30\n        item.canUseNetworkResourcesForLiveStreamingWhilePaused = false\n        installItemObservers(for: item)\n''','''        // Let AVFoundation adapt buffering to throughput and decoder cost.\n        // Large fixed buffers increase system-resource demand.\n        item.preferredForwardBufferDuration = 0\n        item.canUseNetworkResourcesForLiveStreamingWhilePaused = false\n        installItemObservers(for: item)\n        installBufferObservers(for: item)\n''')
replace_once('''            Task { @MainActor in\n                guard let self else { return }\n                switch item.status {\n''','''            Task { @MainActor in\n                guard let self, self.player.currentItem === item else { return }\n                switch item.status {\n''')
replace_once('''                    guard self.player.currentItem === item else { return }\n                    self.updateDuration(using: item.duration.seconds)\n''','''                    self.updateDuration(using: item.duration.seconds)\n''')
marker = '''    private func handlePlaybackFailure() {\n'''
insert = '''    private func installBufferObservers(for item: AVPlayerItem) {\n        itemBufferObservations.removeAll()\n\n        let empty = item.observe(\\.isPlaybackBufferEmpty, options: [.new]) { [weak self] item, _ in\n            Task { @MainActor in\n                guard let self, self.player.currentItem === item else { return }\n                if item.isPlaybackBufferEmpty, self.wantsPlayback {\n                    self.schedulePlaybackRecovery()\n                }\n            }\n        }\n        let likelyToKeepUp = item.observe(\\.isPlaybackLikelyToKeepUp, options: [.new]) { [weak self] item, _ in\n            Task { @MainActor in\n                guard let self, self.player.currentItem === item else { return }\n                guard item.isPlaybackLikelyToKeepUp else { return }\n                self.recoveryTask?.cancel()\n                self.recoveryTask = nil\n                self.recoveryAttempt = 0\n                if self.wantsPlayback, self.player.timeControlStatus != .playing {\n                    self.configureAudioSession()\n                    self.player.play()\n                }\n            }\n        }\n        itemBufferObservations = [empty, likelyToKeepUp]\n    }\n\n'''
if marker not in text:
    raise SystemExit('handlePlaybackFailure marker missing')
text = text.replace(marker, insert + marker, 1)
replace_once('''    private func schedulePlaybackRecovery() {\n        guard wantsPlayback, currentSong != nil, recoveryTask == nil else { return }\n        isBuffering = true\n        recoveryTask = Task { [weak self] in\n            try? await Task.sleep(for: .milliseconds(900))\n            guard let self else { return }\n            defer { self.recoveryTask = nil }\n            guard !Task.isCancelled, self.wantsPlayback else { return }\n\n            self.configureAudioSession()\n            self.player.playImmediately(atRate: 1)\n            try? await Task.sleep(for: .seconds(3))\n            guard !Task.isCancelled else { return }\n\n            if self.player.timeControlStatus != .playing, self.wantsPlayback {\n                self.recoveryAttempt += 1\n                if self.recoveryAttempt <= 2 {\n                    self.loadCurrentItem(\n                        compatibilityFormat: self.activeCompatibilityFormat,\n                        resumeFrom: self.elapsed\n                    )\n                } else {\n                    self.handlePlaybackFailure()\n                }\n            }\n        }\n    }\n''','''    private func schedulePlaybackRecovery() {\n        guard wantsPlayback, currentSong != nil, recoveryTask == nil else { return }\n        isBuffering = true\n        recoveryTask = Task { [weak self] in\n            try? await Task.sleep(for: .milliseconds(1_250))\n            guard let self else { return }\n            defer { self.recoveryTask = nil }\n            guard !Task.isCancelled, self.wantsPlayback,\n                  let item = self.player.currentItem else { return }\n\n            if item.isPlaybackLikelyToKeepUp || !item.isPlaybackBufferEmpty {\n                self.configureAudioSession()\n                self.player.play()\n                return\n            }\n\n            try? await Task.sleep(for: .seconds(3))\n            guard !Task.isCancelled, self.wantsPlayback,\n                  self.player.currentItem === item else { return }\n            guard self.player.timeControlStatus != .playing else { return }\n\n            self.recoveryAttempt += 1\n            if self.recoveryAttempt <= 2 {\n                self.loadCurrentItem(\n                    compatibilityFormat: self.activeCompatibilityFormat,\n                    resumeFrom: self.elapsed\n                )\n            } else {\n                self.handlePlaybackFailure()\n            }\n        }\n    }\n''')
replace_once('''                if Date().timeIntervalSince(self.lastQueueSaveRequest) >= 15 {\n''','''                if Date().timeIntervalSince(self.lastQueueSaveRequest) >= 30 {\n''')
path.write_text(text)
